# Generated by Django 4.1 on 2023-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('Book_Title', models.CharField(max_length=200)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Year_Of_Publication', models.IntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Image_URL_S', models.URLField()),
                ('Image_URL_M', models.URLField()),
                ('Image_URL_L', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(unique=True)),
                ('Location', models.CharField(max_length=100)),
                ('Age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('ISBN', models.CharField(max_length=13)),
                ('Book_Rating', models.IntegerField()),
            ],
            options={
                'unique_together': {('User_ID', 'ISBN')},
            },
        ),
    ]
