# Generated by Django 4.1 on 2023-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
